language: java
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn clean package -DskipTests=true
notifications:
  email: false
  slack: capgemax:7MDJtZvUxLRcMITeBaRwZp1a
